/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tambah.java
 *
 * Created on Jun 2, 2012, 6:36:17 AM
 */
package Librairie;
import javax.swing.JFrame;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author VANY
 */
//import Librairie.User1.NIOCopier;
import java.util.logging.Level;
import java.util.logging.Logger;


public class AddBook extends javax.swing.JFrame {
PreparedStatement pst;
ResultSet rs;
 Connection connection;
    public AddBook() throws Exception {
        
        initComponents();
        
       try {
            connection = DriverManager.getConnection("jdbc:sqlite:data.db");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }




    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        titre = new javax.swing.JTextField();
        auteur = new javax.swing.JTextField();
        btnRetour = new komponenMakeOver.buttonMakeOver();
        buttonMakeOver6 = new komponenMakeOver.buttonMakeOver();
        buttonMakeOver8 = new komponenMakeOver.buttonMakeOver();
        btn_add = new komponenMakeOver.buttonMakeOver();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(153, 102, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CODE LIVRE       :");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(10, 100, 110, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TITRE              :");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(20, 130, 100, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AUTEUR           :  ");
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(20, 160, 120, 16);
        jDesktopPane1.add(code);
        code.setBounds(140, 100, 310, 22);
        jDesktopPane1.add(titre);
        titre.setBounds(140, 130, 310, 22);
        jDesktopPane1.add(auteur);
        auteur.setBounds(140, 160, 310, 22);

        btnRetour.setForeground(new java.awt.Color(255, 255, 255));
        btnRetour.setText("Retour");
        btnRetour.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btnRetour);
        btnRetour.setBounds(60, 220, 190, 40);

        buttonMakeOver6.setForeground(new java.awt.Color(255, 255, 255));
        buttonMakeOver6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jDesktopPane1.add(buttonMakeOver6);
        buttonMakeOver6.setBounds(-10, 70, 540, 10);

        buttonMakeOver8.setForeground(new java.awt.Color(255, 255, 255));
        buttonMakeOver8.setText("Ajouter un livre");
        buttonMakeOver8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        buttonMakeOver8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMakeOver8ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(buttonMakeOver8);
        buttonMakeOver8.setBounds(0, 0, 520, 80);

        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("Sauvegarder");
        btn_add.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btn_add);
        btn_add.setBounds(270, 220, 180, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
              String c,t,a;
c = code.getText();
t = titre.getText();
a = auteur.getText();
try {
pst = connection.prepareStatement("insert into livres(code_livre,titre,auteur)values(?,?,?)");
pst.setString(1, c);
pst.setString(2, t);
pst.setString(3, a);
pst.executeUpdate();
JOptionPane.showMessageDialog(null, "Livre ajouté!!!!!");

          
code.setText("");
titre.setText("");
auteur.setText("");
code.requestFocus();
   }
 
catch (SQLException e1)
        {
e1.printStackTrace();
}                          
    }//GEN-LAST:event_btn_addActionPerformed

private void btnRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourActionPerformed
dispose();
              
            Home home  = new Home();
            home.setTitle("Librerie Syrine");
            home.setVisible(true);
       
}//GEN-LAST:event_btnRetourActionPerformed

    private void buttonMakeOver8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMakeOver8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMakeOver8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
      //  Conex conn =  new Conex();
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new AddBook().show();
                } catch (Exception ex) {
                    Logger.getLogger(AddBook.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField auteur;
    private komponenMakeOver.buttonMakeOver btnRetour;
    private komponenMakeOver.buttonMakeOver btn_add;
    private komponenMakeOver.buttonMakeOver buttonMakeOver6;
    private komponenMakeOver.buttonMakeOver buttonMakeOver8;
    private javax.swing.JTextField code;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField titre;
    // End of variables declaration//GEN-END:variables
}
